baseURL = 'https://1oop.github.io/blog/'
languageCode = 'en-us'
title = 'Adam Zhang'
theme = 'stack'

[[module.imports]]
path = "github.com/CaiJimmy/hugo-theme-stack/v3"

[menu]
main = [
    # {name = "Home", url = "/", weight = 10, params = {newTab = true, icon = "home"}},
]

[params.sidebar]
    emoji = "🇨🇳"
    avatar = {enabled = true, local = true, src = "img/avatar.jpg"}

# [related]
#     includeNewer = true
#     threshold = 60
#     toLower = false
#     indices = [
#         {name = "tags", weight = 100},
#         {name = "categories", weight = 200}
#     ]

[params.widgets]
homepage = [
    {type = "search"},
    {type = "toc"},
    {type = "categories", params = {limit = 10}},
    {type = "tag-cloud", params = {limit = 10}}
]

page = [
    {type = "toc"}
    ]


[params.article]
    math = true
    toc = true
    readingTime = false

[params.opengraph]


[params.defaultImage.opengraph]
    enable = false
    local = false
    src = "assets/img/default.jpeg"
    

